export const UPDATE_MATTRESSES = "UPDATE_MATTRESSES";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const TOGGLE_CART = "TOGGLE_CART";

export const UPDATE_VENDORS = "UPDATE_VENDORS";
export const UPDATE_CURRENT_VENDOR = "UPDATE_CURRENT_VENDOR";
